In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split


In [4]:
df=pd.read_csv("cars.csv")

In [5]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

# 1. OneHotEncoding using Pandas

In [8]:
# in this get dummies,drop_first is used for droping first dummy variable
pd.get_dummies(df,columns=['fuel','owner'],dtype='int32',drop_first=True)

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000            1         0            0   
1       Skoda     120000         370000            1         0            0   
2       Honda     140000         158000            0         0            1   
3     Hyundai     127000         225000            1         0            0   
4      Maruti     120000         130000            0         0            1   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000            0         0            1   
8124  Hyundai     119000         135000            1         0            0   
8125   Maruti     120000         382000            1         0            0   
8126     Tata      25000         290000            1         0            0   
8127     Tata      25000         290000            1         0            0   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                              0                   0                     0   
1                              0                   1                     0   
2                              0                   0                     0   
3                              0                   0                     0   
4                              0                   0                     0   
...                          ...                 ...                   ...   
8123                           0                   0                     0   
8124                           1                   0                     0   
8125                           0                   0                     0   
8126                           0                   0                     0   
8127                           0                   0                     0   

      owner_Third Owner  
0                     0  
1                     0  
2                     1  
3                     0  
4                     0  
...                 ...  
8123                  0  
8124                  0  
8125                  0  
8126                  0  
8127                  0  

[8128 rows x 10 columns]

# OneHotEncoding using sklearn

In [10]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.3,random_state=0)
x_train

brand  km_driven    fuel         owner
5224        Tata      20000  Petrol   First Owner
520       Maruti      30000  Petrol   First Owner
36        Maruti      15000  Petrol   First Owner
5782        Ford      53000  Diesel   First Owner
6522   Chevrolet     120000  Diesel   First Owner
...          ...        ...     ...           ...
4931        Tata      70000  Diesel   Third Owner
3264        Ford     100000  Diesel  Second Owner
1653     Hyundai      90000  Petrol  Second Owner
2607  Volkswagen      90000  Diesel   First Owner
2732     Hyundai     110000  Petrol   First Owner

[5689 rows x 4 columns]

In [11]:
x_test

brand  km_driven    fuel         owner
3558   Hyundai      40000  Diesel   First Owner
233   Mahindra      70000  Diesel   First Owner
7952    Maruti       5000  Petrol   First Owner
572     Maruti     120000  Petrol   Third Owner
6960     Lexus      20000  Petrol   First Owner
...        ...        ...     ...           ...
965     Maruti       5000  Petrol   First Owner
172       Ford       9500  Petrol   First Owner
1428      Ford      35000  Diesel   First Owner
2433  Mahindra     110000  Diesel  Second Owner
483     Maruti      80000  Diesel   First Owner

[2439 rows x 4 columns]

In [13]:
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [24]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']])
x_train_new

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [25]:
x_test_new=ohe.transform(x_test[['fuel','owner']])
x_test_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [21]:
x_train_new.shape

(5689, 7)

In [22]:
x_test_new.shape

(2439, 7)

In [57]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new)).shape

(5689, 9)

# onehotencoding with top categories

In [32]:
counts=df['brand'].value_counts()

In [29]:
df['brand'].nunique()

32

In [31]:
thresold=100
repl=counts[counts<=thresold].index
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [55]:
pd.get_dummies(df['brand'].replace(repl,'uncommon'),dtype='int32',drop_first=True)

Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Renault  Skoda  Tata  \
0             0     0      0        0         0       1        0      0     0   
1             0     0      0        0         0       0        0      1     0   
2             0     0      1        0         0       0        0      0     0   
3             0     0      0        1         0       0        0      0     0   
4             0     0      0        0         0       1        0      0     0   
...         ...   ...    ...      ...       ...     ...      ...    ...   ...   
8123          0     0      0        1         0       0        0      0     0   
8124          0     0      0        1         0       0        0      0     0   
8125          0     0      0        0         0       1        0      0     0   
8126          0     0      0        0         0       0        0      0     1   
8127          0     0      0        0         0       0        0      0     1   

      Toyota  Volkswagen  uncommon  
0          0           0         0  
1          0           0         0  
2          0           0         0  
3          0           0         0  
4          0           0         0  
...      ...         ...       ...  
8123       0           0         0  
8124       0           0         0  
8125       0           0         0  
8126       0           0         0  
8127       0           0         0  

[8128 rows x 12 columns]

In [43]:
x_train['brand'] = x_train['brand'].replace(repl, 'uncommon')
x_test['brand'] = x_test['brand'].replace(repl, 'uncommon')

In [56]:
ohe1=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)
x_train_brand=ohe1.fit_transform(x_train[['brand']])
x_test_brand=ohe1.transform(x_test[['brand']])
x_train_brand

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [54]:
np.hstack((x_train_brand,x_train[['km_driven']].values,x_train_new)).shape

(5689, 20)

In [58]:
np.hstack((x_test_brand,x_test[['km_driven']].values,x_test_new)).shape

(2439, 20)